### ISSUE TITLE
node-gyp error - when installing it uses deprecated node-gyp version 3.8

### ISSUE THREAD

**Issue by Redstonerayy** [Johannes-Schiel/ud-basic-webdev-setup#21]
When copying the package.json and installing, i get the error, that gulp-sass could not be build. The error seems to come from node-sass or gulp-sass using node-gyp v3.8 to build, which is to old to build the package. Is there a fix or something to consider before installing to remove this error?

Error Message
`
npm ERR! code 1
npm ERR! path C:\Users\Anton\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\nodejs\node.exe C:\Users\Anton\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\Anton\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.11.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Anton\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Anton\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Anton\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Anton\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Anton\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Anton\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Anton\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Anton\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Anton\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Anton\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Anton\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Anton\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\Anton\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\Anton\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.11.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anton\AppData\Local\npm-cache\_logs\2021-03-18T08_19_57_091Z-debug.log
`

**Comment by Tracer1337** [comment]
> npm ERR! gyp verb which failed Error: not found: python2

> npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack File "", line 1
npm ERR! gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax

This is an error with Python. Make sure a recent version of Python3 is installed and no other version collides with it in PATH.

**Comment by Redstonerayy** [comment]
Thank you, i also messed around a bit with this, but i found an alternative. I use gulp-dart-sass, it works the same
